variables:
  buildConfiguration: 'Release'
  netSdkVersion: '9.x'

jobs:
- job: BuildAndRunCodeAnalysis
  displayName: Build and run code analysis
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: Set up .NET SDK
    inputs:
      version: $(netSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: Build solution with code analysis
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -warnaserror

- job: RunTests
  displayName: Run tests on
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
      macOS:
        imageName: 'macOS-latest'
      Windows:
        imageName: 'windows-latest'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UseDotNet@2
    displayName: Set up .NET SDK
    inputs:
      version: $(netSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -p:RunAnalyzers=false
  - task: DotNetCoreCLI@2
    displayName: Run tests
    timeoutInMinutes: 15
    inputs:
      command: test
      projects: 'test/*/*Tests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build