variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildWithCodeAnalysisAndRunTests
  displayName: Build with code analysis and run tests
  pool:
    vmImage: windows-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution with code analysis
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -warnaserror
  - task: DotNetCoreCLI@2
    displayName: Run tests
    timeoutInMinutes: 15
    inputs:
      command: test
      projects: 'test/*/*Tests.csproj'
      arguments: -c $(buildConfiguration) --no-build